title: Faizul Rakib Sayem
logo: /assests/Sayem_2.jpg
#description: text below image
#show_downloads: true
description: >
  PhD Student in Electrical Engineering at University of Central Florida.  
  Research in Vision-Language Models, Out-of-Distribution Detection,  
  and Multi-label Learning. 
theme: jekyll-theme-minimal



