title: Faizul Rakib Sayem
logo: /assests/Sayem_2.jpg
description: I am currently a 2nd year PhD student at the University of Central Florida. 
I am working on weak supervision and noise learning with vision language modeling.
My research interest lies in vision language modeling, LLM, object hallucination mitigation, and alignment with human feedback. 
show_downloads: false
theme: jekyll-theme-minimal



